"""add_iam_full

Revision ID: 1ede58476c74
Revises: 9931eef2d342
Create Date: 2026-05-22 17:07:50.582787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ede58476c74'
down_revision: Union[str, Sequence[str], None] = '9931eef2d342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('title_ru', sa.String(length=250), nullable=False, comment='Название группы на русском'),
    sa.Column('title_kk', sa.String(length=250), nullable=True, comment='Название группы на казахском'),
    sa.Column('title_en', sa.String(length=250), nullable=True, comment='Название группы на английском'),
    sa.Column('description_ru', sa.Text(), nullable=True, comment='Описание группы на русском'),
    sa.Column('description_kk', sa.Text(), nullable=True, comment='Описание группы на казахском'),
    sa.Column('description_en', sa.Text(), nullable=True, comment='Описание группы на английском'),
    sa.Column('value', sa.String(length=280), nullable=False, comment='Уникальное значение группы'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_value'), 'groups', ['value'], unique=True)
    op.create_table('organizations',
    sa.Column('full_name', sa.String(length=250), nullable=False, comment='Полное название организации'),
    sa.Column('short_name', sa.String(length=250), nullable=True, comment='Краткое название организации'),
    sa.Column('address', sa.String(length=250), nullable=True, comment='Адрес организации'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Телефон'),
    sa.Column('email', sa.String(length=250), nullable=True, comment='Email'),
    sa.Column('bin', sa.String(length=12), nullable=False, comment='БИН организации'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Организация активна'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_bin'), 'organizations', ['bin'], unique=True)
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=False)
    op.create_index(op.f('ix_organizations_phone'), 'organizations', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Имя'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Фамилия'),
    sa.Column('patronymic', sa.String(length=100), nullable=True, comment='Отчество'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Логин'),
    sa.Column('email', sa.String(length=250), nullable=False, comment='Email'),
    sa.Column('phone', sa.String(length=50), nullable=False, comment='Телефон'),
    sa.Column('gender', sa.SmallInteger(), nullable=False, comment='Пол 0 - не определен, 1 - Мужской, 2 - Женский'),
    sa.Column('birthdate', sa.Date(), nullable=True, comment='Дата рождения'),
    sa.Column('image', sa.String(length=500), nullable=True, comment='Аватар пользователя'),
    sa.Column('password_hash', sa.String(length=250), nullable=False, comment='Пароль'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Пользователь активен'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Пользователь верифицирован'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Последний раз был активен'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_groups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uix_user_groups')
    )
    op.create_table('user_organizations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uix_user_organizations')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uix_user_roles')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('user_organizations')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_phone'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_bin'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_groups_value'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
