"""init_iam

Revision ID: 9931eef2d342
Revises: 
Create Date: 2026-05-22 14:42:53.250545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9931eef2d342'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('title_ru', sa.String(length=250), nullable=False, comment='Название роли на русском'),
    sa.Column('title_kk', sa.String(length=250), nullable=True, comment='Название роли на казахском'),
    sa.Column('title_en', sa.String(length=250), nullable=True, comment='Название роли на английском'),
    sa.Column('description_ru', sa.Text(), nullable=True, comment='Описание роли на русском'),
    sa.Column('description_kk', sa.Text(), nullable=True, comment='Описание роли на казахском'),
    sa.Column('description_en', sa.Text(), nullable=True, comment='Описание роли на английском'),
    sa.Column('value', sa.String(length=280), nullable=False, comment='Уникальное значение permissions'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_value'), 'permissions', ['value'], unique=True)
    op.create_table('roles',
    sa.Column('title_ru', sa.String(length=250), nullable=False, comment='Название роли на русском'),
    sa.Column('title_kk', sa.String(length=250), nullable=True, comment='Название роли на казахском'),
    sa.Column('title_en', sa.String(length=250), nullable=True, comment='Название роли на английском'),
    sa.Column('description_ru', sa.Text(), nullable=True, comment='Описание роли на русском'),
    sa.Column('description_kk', sa.Text(), nullable=True, comment='Описание роли на казахском'),
    sa.Column('description_en', sa.Text(), nullable=True, comment='Описание роли на английском'),
    sa.Column('value', sa.String(length=280), nullable=False, comment='Уникальное значение роли'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_value'), 'roles', ['value'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uix_role_permission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_value'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_value'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
